### ISSUE TITLE
Repeater frequency in yaml file stored (and programmed?) with offset (version issue/conflict)?

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#306] opened 2023-02-10 21:25 UTC
Using qdmr 0.11.2 from PPA on Ubuntu 22.04, while testing the Github version in a local build directory:

For DB0BRO, https://www.repeaterbook.com/api/exportROW.php?callsign=DB0BRO%25 returns

Frequency | "439.137500"
Input Freq | "431.53750"

which is what qdmr displays in the channel config. Stored in the yaml file is, however

rxFrequency: 439.13749999999999
txFrequency: 431.53750000000002

That happens with all repeaters I tried. I checked older stored yaml files - that only changed recently. Is there a qdmr config file that stores an offset? From what I can gather, that happens since I test the version from github parallel to the regular installed version - with different yaml files, but as the same user. In .config/DM3MAT/qdmr.conf I could not find anything that causes that offset? And is it only a cosmetic issue or what value is actually programmed into the radio? The local build from the github sources has the same offset - tried with an empty config and added just one digital channel. I also deleted .local/share/DM3MAT/qdmr/repeaterbook.query.json - same result. Will try as a different user who never started qdmr before..

**Comment by hmatuschek** [comment] 2023-02-11 08:09
This is actually a duplicate of #249, and this one will be fixed with release 0.12.0. Until then, the frequencies are stored in MHz as floating point numbers. Floating point numbers, however, cannot store large integer values precisely. So this is a rounding error. In future, the frequency will be stored as a unsigned long long in Hz.

**Closed by hmatuschek** 2023-02-11 08:09 UTC
Labels: duplicate
