### ISSUE TITLE
Unknown TyT device 'DM-1701'

### ISSUE THREAD

**Issue by dcorl99** [hmatuschek/qdmr#237] opened 2022-08-04 17:47 UTC
Hi, I'm trying to make my RT-84 work with qdmr. Long story short it looks like the work has already been done, there is mention of dm-1701 in #136 
The output of "dmrconf --verbose detect"  displays: 
ERROR in tyt_interface.cc@44: Unknown TyT device 'DM-1701'.
ERROR in autodetect.cc@117: Cannot auto-detect radio.
I did not see an entry in the tyt_interface.cc for the DM-1701
What would be the best way to add this?

BTW - Debian Bullseye, complied without issues.

Thanks, Dale

**Comment by hmatuschek** [comment] 2022-08-04 18:42
Yes, it is implemented but untested and the callsign db is still missing. However, the important lines for the detection are 
https://github.com/hmatuschek/qdmr/blob/1fb0fc5732d4dc90e1adf470997aae389efa6b9a/lib/tyt_interface.cc#L41
and
https://github.com/hmatuschek/qdmr/blob/1fb0fc5732d4dc90e1adf470997aae389efa6b9a/lib/radio.cc#L97

Maybe this is an embarrassing bug in L41 in tyt_interface.cc and the string should be `DM-1701` instead of `1701`. I could fix that any you may test it by compiling qdmr from the sources.

**Comment by hmatuschek** [comment] 2022-08-05 06:46
Fixed the line 41 ind tyt_interface.cc. I've never got a wireshark capture from this device, hence I never knew how the device identifies itself. I've just cross checked with dmrconfig and indeed the string should be `DM-1701`. 

https://github.com/OpenRTX/dmrconfig/blob/9e65be7ab704297ccb12dc6f6300a28039abc3a6/radio.c#L50

**Comment by dcorl99** [comment] 2022-08-05 13:54
I have wireshark on the computer that I'm running qdmr on so I should be able to provide the capture. Will review and try to figure out how to do it.

I'm going to try and re-compile qdmr with the changes to the tyt_interface.cc  you made. 

Thanks, Dale

**Comment by dcorl99** [comment] 2022-08-05 15:53
The re-compile went well, I now have a new error message: "Cannot connect to radio"
I think I have a good wireshark capture. The radio was plugged into the USB port but did not display PC until I pressed the  Detect connected radios icon within QDMR. This happened at about the mid point in the capture. I hope this helps and please let me know if you need something else on the capture. Thanks, Dale 
[RT_84usbmon5.pcapng.gz](https://github.com/hmatuschek/qdmr/files/9270051/RT_84usbmon5.pcapng.gz)

**Comment by hmatuschek** [comment] 2022-08-05 18:04
Thanks for testing it. If you start qdmr from the command line, there
should be much more debug messages. Could you also attach them here?

dcorl99 ***@***.***> schrieb am Fr., 5. Aug. 2022, 17:53:

**Comment by hmatuschek** [comment] 2022-08-06 06:36
Thanks for the capture, it looks ok but I haven't looked at it in detail. However, the protocol should be the same as the one for other TyT or Retevis devices, so I believe that the issue is not in the communication protocol implementation. But rather somewhere else.

**Comment by dcorl99** [comment] 2022-08-06 15:12
Here is the requested output from running qdmr from cli. Hope this helps, Dale
[cli_debug2.txt](https://github.com/hmatuschek/qdmr/files/9275304/cli_debug2.txt)

**Comment by hmatuschek** [comment] 2022-08-07 12:27
The messages looks good. However, there are no error messages indicating what when wrong. I've added some more debug messages.

**Comment by dcorl99** [comment] 2022-08-07 16:09
There was a little type error in line 34 of tyt_interface.cc 
  _ident = RadioInfo::byID(RadioInfo::MD380);

I changed it to MD390 and it complied. 

I was able to connect to the radio and download the codeplug it had on it. :-)

Attached is the cli output. Seems the radio quickly goes to sleep but it is working.

Please let me know if you want me to test anything else. 

Thanks, Dale
[cli_debug3b.txt](https://github.com/hmatuschek/qdmr/files/9277111/cli_debug3b.txt)

**Comment by hmatuschek** [comment] 2022-08-07 16:23
In fact, MD380 is an alias for MD390

https://github.com/hmatuschek/qdmr/blob/22225f4c36ee83cfc9dbad519bd54aadee24b344/lib/radioinfo.hh#L26

Anyway, this should not affect the detection of the DM-1701.

**Comment by hmatuschek** [comment] 2022-08-07 16:32
Btw, you do not need to detect the radio before reading or writing the codeplug. This is part of the read/write process anyway.

**Comment by hmatuschek** [comment] 2022-08-07 16:50
I've just noticed, that I do not have a capture of the call-sign db write. This was the last thing missing from the issue #136. So, if you do not find any major issues with the DM-1701 codeplug, I would close this issue and would continue with the call-sign db in issue #136.

**Comment by dcorl99** [comment] 2022-08-07 17:51
> In fact, MD380 is an alias for MD390
> 
> https://github.com/hmatuschek/qdmr/blob/22225f4c36ee83cfc9dbad519bd54aadee24b344/lib/radioinfo.hh#L26
> 
> Anyway, this should not affect the detection of the DM-1701.

I got an error when I tried the first time to compile that's why I took a closer look.  Just thought I should mention it in case somebody else has trouble. 

[  1%] Building CXX object lib/CMakeFiles/libdmrconf.dir/tyt_interface.cc.o
/home/delcha/QDMR/qdmr-0.10.2/lib/tyt_interface.cc: In constructor ‘TyTInterface::TyTInterface(const USBDeviceDescriptor&, const ErrorStack&, QObject*)’:
/home/delcha/QDMR/qdmr-0.10.2/lib/tyt_interface.cc:34:41: error: ‘MD380’ is not a member of ‘RadioInfo’
   34 |     _ident = RadioInfo::byID(RadioInfo::MD380);
      |                                         ^~~~~
make[2]: *** [lib/CMakeFiles/libdmrconf.dir/build.make:878: lib/CMakeFiles/libdmrconf.dir/tyt_interface.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:197: lib/CMakeFiles/libdmrconf.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by dcorl99** [comment] 2022-08-07 17:52
> Btw, you do not need to detect the radio before reading or writing the codeplug. This is part of the read/write process anyway.

Ok, thanks will try next time I work on the radio.

**Comment by dcorl99** [comment] 2022-08-07 17:55
> I've just noticed, that I do not have a capture of the call-sign db write. This was the last thing missing from the issue #136. So, if you do not find any major issues with the DM-1701 codeplug, I would close this issue and would continue with the call-sign db in issue #136.

Might be a while before I test or work on the radio so if you want to close I can always start another if needed.

Thanks for the help and work, awesome program! I don't run Windows computers anymore so it's really nice to see this program :-)

**Comment by hmatuschek** [comment] 2022-08-07 18:40
Ok, I'll close this one then and continue on #136 then.

**Closed by hmatuschek** 2022-08-07 18:40 UTC
Labels: bug, DM-1701
