### ISSUE TITLE
[Feature] Workflow to Add and View Talkgroups By Repeaters

### ISSUE THREAD

**Issue by memtech3** [hmatuschek/qdmr#134] opened 2021-09-14 04:11 UTC
Instead of having to manually create a new channel entry for each talkgroup on a repeater, allow users to select a view that shows talkgroups as a sub item of repeaters and add talkgroups to repeaters.  If a set of channels exist with the same prefix and frequencies, group them together. When someone adds talkgroups to a repeater, create channel entries in the codeplug with the repeater name as the prefix for the talkgroup name (repeater name talkgroup name).

**Comment by hmatuschek** [comment] 2021-11-06 09:46
If you don't mind, I would move this issue to discussions. I believe that it would be helpful to have a more broader discussion about how such a wizard should look like.

**Comment by hmatuschek** [comment] 2021-11-06 09:55
Actually, I mark this issue as a duplicate of #114 as it is closely related and move the latter one to discussions.

**Closed** 2021-11-06 09:55 UTC
Labels: duplicate
