### ISSUE TITLE
idea: automatically add repeaters for a location

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#114] opened 2021-05-17 13:18 UTC
QDMR already uses a database to look up repeaters, so my idea is to allow users to enter a location and then all repeaters within a specific radius (like 50 km) get added to the codeplug, sorting them alphabetically or by distance.

Maybe they could even be added to a specific zone, like a "London zone" or whatever place you're adding. :D 

I think that makes programming radios a lot easier and a lot less work.

Travelling to a place you don't know? Enter a location and all repeaters in that area get added automatically. :D 

What do you think?

**Comment by hmatuschek** [comment] 2021-05-25 09:07
I thought about that at the very beginning. In earlier versions of qdmr, there was a disabled button in the toolbar labelled "Wizard" to assemble codeplugs in a similar way you described. This however, is not that simple. In particular with the information provided by https://repeatermap.de. The only reliable information I can extract are the frequencies and calls of the repeater. 

For analog channels I also need the CTCSS or DCS settings which are only provided as plain text. Otherwise, it is possible.

For DMR channels it gets more complicated. First of all, I need the color code (again in plaintext in repeatermap). Then I need the network the repeater is associated with. For DMR+ it would be easy, as I would simply create two channels for each repeater with TG9 as the TX contact. For Brandbmeister it is even more complicated: Somehow I need the TX contacts for TS1 and TS2. The latter could be achieved by asking the user for the RX group lists for the two timeslots. Then I could create a channel for each entry of these RX group lists.

I can get this additional information from https://repeaterbook.com. There CTCSS, DCS, colorcode etc is stored in a separate field can could be read reliable. Unfortunately, the access policies of repeaterbook are quiet restrictive. Also, I cannot search repeaterbook for a locator. Just for a country.

**Comment by ra1nb0w** [comment] 2021-08-29 06:01
maybe a useful site https://www.iz8wnh.it

**Comment by hmatuschek** [comment] 2021-10-31 11:23
Similarly to #157, how about moving this issue to discussions?

**Comment by hmatuschek** [comment] 2021-11-06 09:56
I've marked the #134 as a duplicate of this one, so we have a common topic for the discussion.

**Closed** 2021-11-06 09:56 UTC
Labels: enhancement, GUI
