### ISSUE TITLE
thinks DM1701/opengd77 is a DR-1801UV

### ISSUE THREAD

**Issue by mert817** [hmatuschek/qdmr#479] opened 2024-09-14 00:34 UTC
mert@mert-Inspiron-15-3567:~$ dmrconf -V -D /dev/usbTTY0 -R dm1701 detect
Debug in cli/autodetect.cc@40: Autodetect radios.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@157: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/c7000device.cc@236: Search for C7000 devices matching VID:PID 1206:227.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@157: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/usbserial.cc@136: Search for serial ports.
Debug in lib/usbserial.cc@141: Found ttyUSB0 (USB 67b:2303).
Debug in lib/c7000device.cc@236: Search for C7000 devices matching VID:PID 1206:227.
Info in cli/autodetect.cc@51: Found 1 device(s):
Info in cli/autodetect.cc@53:   Serial interface 'ttyUSB0'.
ERROR in cli/autodetect.cc@67: Device handle '/dev/usbTTY0' not found in:
Device 'ttyUSB0'
 Type:        Serial interface 'ttyUSB0'
 Description: Possibly interfacing Baofeng DR-1801UV

ERROR in cli/detect.cc@15: Cannot detect radio: 
  In autodetect.cc:67: Device handle '/dev/usbTTY0' not found in:
Device 'ttyUSB0'
 Type:        Serial interface 'ttyUSB0'
 Description: Possibly interfacing Baofeng DR-1801UV

mert@mert-Inspiron-15-3567:~$ dmrconf -V -D /dev/usbTTY0 --R opengd77 detect
Debug in cli/autodetect.cc@40: Autodetect radios.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@157: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/c7000device.cc@236: Search for C7000 devices matching VID:PID 1206:227.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@157: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/usbserial.cc@136: Search for serial ports.
Debug in lib/usbserial.cc@141: Found ttyUSB0 (USB 67b:2303).
Debug in lib/c7000device.cc@236: Search for C7000 devices matching VID:PID 1206:227.
Info in cli/autodetect.cc@51: Found 1 device(s):
Info in cli/autodetect.cc@53:   Serial interface 'ttyUSB0'.
ERROR in cli/autodetect.cc@67: Device handle '/dev/usbTTY0' not found in:
Device 'ttyUSB0'
 Type:        Serial interface 'ttyUSB0'
 Description: Possibly interfacing Baofeng DR-1801UV

ERROR in cli/detect.cc@15: Cannot detect radio: 
  In autodetect.cc:67: Device handle '/dev/usbTTY0' not found in:
Device 'ttyUSB0'
 Type:        Serial interface 'ttyUSB0'
 Description: Possibly interfacing Baofeng DR-1801UV

**Comment by hmatuschek** [comment] 2024-09-30 17:43
It is a duplicate of #394. Conserning the identification issue, see #485.

**Closed by hmatuschek** 2024-09-30 17:43 UTC
Labels: duplicate

**Comment by mert817** [comment] 2025-01-03 21:57
I have verified that v0.12.1 successfully reads and writes codeplug to my
Baofeng DM1701 with OpenGD77.

One curiosity is that the radio identifies as "Open MD-UV380".  But this is
unimportant.

Thank you for your work.  Merton AC7KY
