### ISSUE TITLE
Codeplug.yaml/rxTone refuses to load after save.

### ISSUE THREAD

**Issue by ikbenkous** [hmatuschek/qdmr#509] opened 2024-12-25 23:03 UTC
This had me scratching my head for hours. I resorted to keeping my codeplugs in a git repo so I could observe changes.
(A **_very_** wise choice if I do say so myself!)

Version tested: 73756feb7ff7571bc86f03f9baf465fd0223444e (latest master as of now?)
Platform: Linux/Ubuntu

qdmr initially loads my `codeplug.yaml` just fine. I can even program my radio (Anytone AT-D878UVII Plus) with it.
Saving it once, it can't load it ever again. Even if I make no changes in qdmr and just save it, the file will still come out with changes (see below).

Output from qdmr:
```
Debug in src/application.cc@360: Load codeplug from '/home/kous/Desktop/codeplug.yaml'.
Debug in lib/config.cc@375: Using format version 0.12.0.
ERROR in lib/configobject.cc@659: 217:14: Cannot parse rxTone of FMChannel: Expected selective call.
ERROR in lib/configobject.cc@1432: 212:4: Cannot parse list.
```
Quick link: https://github.com/hmatuschek/qdmr/commit/98b3cf59e5995655411be6796dcbde950a7cbdca#diff-fc4c3d51eb94be9ed088b2fac3c2491bf7201c3151017560c4ad85e5610eecf9R658-R663

---

Note that the bug triggers on the first `rxTone: ~` line it can find. In this case, it's the APRS VHF entry:

Excerpt from bugged `codeplug.yaml`:
```
[...]
 212 channels:
 213   - analog:
 214       id: ch1
 215       name: APRS VHF
 216       rxOnly: false
 217       admit: Free 
 218       rxTone: ~
 219       txTone: ~
 220       bandwidth: Narrow
 221       anytone:
 222         talkaround: false
 223         frequencyCorrection: 0
 224         handsFree: false
 225         aprsPTT: Off
 226         reverseBurst: false
 227         rxCustomCTCSS: false
 228         txCustomCTCSS: false
 229         customCTCSS: 0
 230         squelchMode: Carrier
 231         scrambler: false
 232       rxFrequency: 144.8 MHz
 233       txFrequency: 144.8 MHz
 234       power: Max 
 235       timeout: !<!default> ""
 236       vox: !<!default> ""
 237       squelch: !<!default> ""
 238   - analog:
 239       id: ch2
 240       name: APRS ISS
 241       rxOnly: false
 242       admit: Free
 [...]
```

---

Here are the types of the changes introduced in my codeplug:

```diff
@@ -259,11 +265,14 @@ channels:
       name: APRS UHF
       rxOnly: false
       admit: Free
+      rxTone: ~
+      txTone: ~
       bandwidth: Narrow
       anytone:
         talkaround: false
         frequencyCorrection: 0
         handsFree: false
+        aprsPTT: Off
         reverseBurst: false
         rxCustomCTCSS: false
         txCustomCTCSS: false
```

```diff
   - analog:
       id: ch77
       name: PI2RKW
       rxOnly: false
       admit: Always
+      rxTone: ~
+      txTone:
+        ctcss: 71.9 Hz
       bandwidth: Narrow
       rxFrequency: 438.125 MHz
       txFrequency: 430.525 MHz
       power: Low
       timeout: !<!default> ""
       vox: !<!default> ""
-      txTone: {ctcss: 71.9000015}
       squelch: !<!default> ""
```

**Comment by ikbenkous** [comment] 2024-12-26 00:39
Bug occurs when Rx Tone and Tx Tone are set to `none` in the UI:
![image](https://github.com/user-attachments/assets/25e5338d-14f7-4cdd-94fb-f77a59af6866)

**Comment by ikbenkous** [comment] 2024-12-26 13:33
I may have found another bug:
https://github.com/hmatuschek/qdmr/blob/ddeb812138fed26dc75665e1818ca37f622b1b73/src/repeaterdatabase.cc#L119-L120

Line 120?

**Comment by hmatuschek** [comment] 2024-12-26 13:59
The problem is a picky CTCSS/DCS parser. One moment...

**Comment by hmatuschek** [comment] 2024-12-26 14:29
Should be fixed in branch `509-subtone-parser-issue`.

**Comment by hmatuschek** [comment] 2024-12-26 14:29
> I may have found another bug:
> 
> https://github.com/hmatuschek/qdmr/blob/ddeb812138fed26dc75665e1818ca37f622b1b73/src/repeaterdatabase.cc#L119-L120
> 
> Line 120?

Uh, that one is mean. Thanks for spotting this one. (also fixed in this branch)

**Comment by ikbenkous** [comment] 2024-12-26 21:54
No, thank you, @hmatuschek, for fixing these two bugs so fast.

The codeplug loads correctly now. I don't know if the "mean one" is fixed as I didn't test it, but I'm already a happy camper with the `rxTone`/`txTone` null values being correctly handled.

**Comment by hmatuschek** [comment] 2024-12-26 22:48
Okay. I'll merge it into master and close this issue. Feel free to reopen it, if you stumble across something fishy.

**Closed** 2024-12-26 22:48 UTC
Labels: bug
