### ISSUE TITLE
Segfault: Trying to detect an MD390G

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#235] opened 2022-08-02 16:14 UTC
```
Debug in usbdevice.cc@217: Search for a device matching VID:PID 483:df11 at bus 1, device 74.
Debug in usbdevice.cc@228: Found device on bus=1, device=74 with 483:df11.
Debug in radio.cc@55: Try to detect radio at USB device in DFU mode: bus 1, device 74.
Debug in dfu_libusb.cc@75: Try to detect USB DFU interface USB device in DFU mode: bus 1, device 74.
Debug in dfu_libusb.cc@89: Matching device found at bus 1, device 74 with vendor ID 483 and product ID df11.
Debug in dfu_libusb.cc@128: Connected to DFU device USB device in DFU mode: bus 1, device 74.
Debug in md390.cc@54: Got frequency range 144.975MHz - 439.887MHz from 566 channels.
ERROR in md390.cc@70: Cannot determine frequency range from channel frequencies between 144.975MHz and 439.887MHz. Will not check frequency ranges.
[1]    243949 segmentation fault  ./qdmr
```

Stock firmware with md380tools.

OS: Debian
Version of qdmr: 0.10.2

**Comment by hmatuschek** [comment] 2022-08-03 10:15
Duplicate of #234, although appearing in a different situation.

**Closed by hmatuschek** 2022-08-03 10:15 UTC
Labels: bug, duplicate, MD-390
